export const ADD_BOARD = "ADD_BOARD";
export const REMOVE_BOARD = "REMOVE_BOARD";
// export const SET_CURRENT_BOARD_ID = "SET_CURRENT_BOARD_ID";
// export const CLEAR_CURRENT_BOARD_ID = "CLEAR_CURRENT_BOARD_ID";
export const SET_CURRENT_BOARD = "SET_CURRENT_BOARD";
export const CLEAR_CURRENT_BOARD = "CLEAR_CURRENT_BOARD";
